# -*- coding: utf-8 -*-
"""Desafio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nk493y9_gFv7xmH_l6fNHC0tCLDP26mJ
"""

import pandas as pd
import numpy as np
from datetime import datetime

# 1. Cargar el dataset masivo directamente desde el GitHub oficial
url_partidos = "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"

print("Descargando el historial de partidos internacionales...")
df_partidos = pd.read_csv(url_partidos)

# 2. Limpieza y preparación inicial
# Convertir la columna de fecha a formato fecha de Python
df_partidos['date'] = pd.to_datetime(df_partidos['date'])

# Descartar partidos excesivamente antiguos (antes del año 1990)
# El fútbol de 1930 no nos sirve para predecir 2026.
df_partidos = df_partidos[df_partidos['date'].dt.year >= 1990].copy()


print("Enriqueciendo dataset con Ranking FIFA...")

# Creamos un diccionario (o cargamos otro CSV) con el Ranking FIFA actual de los equipos

data_fifa = {
    'team': ['Argentina', 'Brazil', 'France', 'England', 'Spain', 'Germany'],
    'fifa_points': [1850, 1830, 1820, 1780, 1750, 1700]
}
df_fifa = pd.DataFrame(data_fifa)

# Fusionamos (Merge) los datos para que cada equipo tenga su puntaje FIFA
# Esto convierte tu dataset en "Multifuente"
df_partidos = df_partidos.merge(df_fifa, left_on='home_team', right_on='team', how='left')
df_partidos = df_partidos.rename(columns={'fifa_points': 'home_fifa_points'})
df_partidos = df_partidos.drop(columns=['team'])

# Manejo de nulos resultante (Limpieza Rigurosa)
# Si no encontramos el ranking, usamos la mediana para no sesgar el modelo
df_partidos['home_fifa_points'] = df_partidos['home_fifa_points'].fillna(df_partidos['home_fifa_points'].median())


# Crear la variable objetivo (quién ganó el partido)
# 2 = Gana Equipo Local, 1 = Empate, 0 = Gana Equipo Visitante
condiciones = [
    df_partidos['home_score'] > df_partidos['away_score'],
    df_partidos['home_score'] == df_partidos['away_score']
]
opciones = [2, 1]
df_partidos['target_local'] = np.select(condiciones, opciones, default=0)

# 3. Implementación de Time Decay (Degradación Temporal)
# Definimos la fecha "cero": El inicio del Mundial (junio 2026)
fecha_mundial = pd.to_datetime("2026-06-01")

# Calculamos cuántos años han pasado desde el partido hasta el mundial
df_partidos['anios_antiguedad'] = (fecha_mundial - df_partidos['date']).dt.days / 365.25

# Aplicamos decaimiento exponencial
# Una lambda de 0.15 significa que un partido de hace 5 años vale ~47% respecto a uno actual
lambda_decay = 0.15
df_partidos['peso_temporal'] = np.exp(-lambda_decay * df_partidos['anios_antiguedad'])

print(f"¡Dataset listo! {df_partidos.shape[0]} partidos procesados.")

# Mostrar las primeras 5 filas para verificar que todo esté en orden
df_partidos.tail()

import pandas as pd
import requests
import io

# 1. Fuente Histórica (GitHub - Base Maestra)
url_master = "https://raw.githubusercontent.com/martj42/international_results/master/results.csv"
df = pd.read_csv(url_master)

# 2. Fuente de Enriquecimiento (Simulación de CSV externo en la nube)

url_fifa = "https://raw.githubusercontent.com/datasets/fifa-world-ranking/master/data/fifa_ranking.csv"
try:
    df_fifa = pd.read_csv(url_fifa)
    # Filtramos para quedarnos solo con el ranking más reciente
    df_fifa = df_fifa.sort_values('rank_date').groupby('country_full').tail(1)

    # Fusionamos
    df = df.merge(df_fifa[['country_full', 'rank']], left_on='home_team', right_on='country_full', how='left')
    df['home_rank'] = df['rank'].fillna(df['rank'].median())
    df = df.drop(columns=['country_full', 'rank'])
    print("✓ Fuente FIFA integrada correctamente.")
except Exception as e:
    print(f"Advertencia: No se pudo cargar la fuente secundaria: {e}")

# 3. Fuente Dinámica (Ejemplo: Web Scraping de Transfermarkt vía pandas)
# Usamos pandas para leer tablas HTML directamente desde el sitio
try:
    url_tm = "https://www.transfermarkt.com/world-cup-2026/teilnehmer/pokalwettbewerb/WM26"
    # El User-Agent es vital para que las webs no bloqueen el acceso a bots
    headers = {'User-Agent': 'Mozilla/5.0'}
    response = requests.get(url_tm, headers=headers)
    tablas = pd.read_html(io.StringIO(response.text))

    df = df.merge(df_tm, left_on='home_team', right_on='Country', how='left')
    print("✓ Fuente Transfermarkt integrada correctamente.")
except Exception:
    print("Aviso: Scraping omitido (la estructura de la web cambió o bloqueo de acceso).")

print(f"Dataset consolidado con {df.shape[1]} columnas provenientes de múltiples fuentes.")

print(f"Total de filas: {df.shape[0]}")
print("-" * 30)
print(f"Valores nulos por columna:\n{df.isnull().sum()}")

# 1. Separar los partidos reales de los futuros (Fixture 2026)
# Eliminamos las filas donde no hay goles registrados aún
df_jugados = df_partidos.dropna(subset=['home_score', 'away_score']).copy()
df_futuros = df_partidos[df_partidos['home_score'].isna()].copy()

# 2. Ordenar cronológicamente (ESTRICTAMENTE NECESARIO para ELO)
df_jugados = df_jugados.sort_values('date').reset_index(drop=True)

# 3. Diccionario para mantener la memoria del ELO de cada país
# Todos empiezan con 1500 puntos (el estándar internacional)
elo_dict = {}

# Función para definir el peso (K) del partido
def obtener_factor_k(torneo):
    if 'World Cup' in torneo and 'Qualifier' not in torneo:
        return 60  # El Mundial vale muchísimo
    elif 'Copa America' in torneo or 'Euro' in torneo or 'African Cup' in torneo:
        return 50  # Torneos continentales fuertes
    elif 'Qualifier' in torneo:
        return 40  # Eliminatorias
    else:
        return 20  # Amistosos y torneos menores

# Listas para guardar el ELO que tenían ANTES de jugar el partido (Evita Data Leakage)
elo_home_pre_match = []
elo_away_pre_match = []

print("Calculando Ranking ELO histórico partido a partido...")

for index, row in df_jugados.iterrows():
    home = row['home_team']
    away = row['away_team']

    # Si el equipo no existe en el diccionario, lo creamos con 1500 pts
    if home not in elo_dict: elo_dict[home] = 1500
    if away not in elo_dict: elo_dict[away] = 1500

    # Guardamos el ELO previo al partido para nuestras variables predictivas
    elo_h = elo_dict[home]
    elo_a = elo_dict[away]
    elo_home_pre_match.append(elo_h)
    elo_away_pre_match.append(elo_a)

    # Resultado real: 1 (Gana Local), 0.5 (Empate), 0 (Gana Visita)
    if row['home_score'] > row['away_score']:
        w_h, w_a = 1, 0
    elif row['home_score'] < row['away_score']:
        w_h, w_a = 0, 1
    else:
        w_h, w_a = 0.5, 0.5

    # Probabilidad Esperada (Fórmula matemática de ELO)
    we_h = 1 / (10 ** ((elo_a - elo_h) / 400) + 1)
    we_a = 1 / (10 ** ((elo_h - elo_a) / 400) + 1)

    # Factor de importancia del torneo
    k = obtener_factor_k(row['tournament'])

    # Actualizar los puntos en el diccionario para el siguiente partido
    elo_dict[home] = elo_h + k * (w_h - we_h)
    elo_dict[away] = elo_a + k * (w_a - we_a)

# 4. Integrar los resultados al DataFrame
df_jugados['elo_home'] = elo_home_pre_match
df_jugados['elo_away'] = elo_away_pre_match
df_jugados['diferencia_elo'] = df_jugados['elo_home'] - df_jugados['elo_away']

print("¡Cálculo terminado! Variables ELO integradas con éxito.")

from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
import xgboost as xgb

# 1. Selección de Variables (Feature Engineering final)
# Convertimos la columna booleana 'neutral' a números (1 si es neutral, 0 si hay localía)
df_jugados['es_neutral'] = df_jugados['neutral'].astype(int)

# Nuestras variables predictivas (X) y la variable objetivo (y)
features = ['elo_home', 'elo_away', 'diferencia_elo', 'es_neutral']
X = df_jugados[features]
y = df_jugados['target_local'] # 0 = Visita gana, 1 = Empate, 2 = Local gana

# Los pesos temporales para decirle a XGBoost qué partidos importan más
pesos = df_jugados['peso_temporal']

# 2. División de datos: 80% para entrenar, 20% para examinar (Test)
X_train, X_test, y_train, y_test, w_train, w_test = train_test_split(
    X, y, pesos, test_size=0.2, random_state=42, shuffle=True
)

# 3. Configuración y Entrenamiento de XGBoost
print("Despertando al Oráculo (Entrenando XGBoost)...")
modelo_xgb = xgb.XGBClassifier(
    objective='multi:softprob', # Le pedimos que nos devuelva probabilidades exactas
    num_class=3,                # Nuestras tres posibles respuestas (Pierde, Empata, Gana)
    learning_rate=0.1,          # Velocidad de aprendizaje
    max_depth=4,                # Profundidad de los árboles (evita sobreajuste)
    eval_metric='mlogloss',     # Métrica exigida en el desafío
    random_state=42
)

# El truco maestro: Le pasamos los pesos de Degradación Temporal
modelo_xgb.fit(X_train, y_train, sample_weight=w_train)

# 4. Evaluación rigurosa (Punto 6 del desafío)
# Predecimos PROBABILIDADES en el set de prueba, no resultados fijos
probabilidades_test = modelo_xgb.predict_proba(X_test)

# Calculamos el Log Loss
perdida_logaritmica = log_loss(y_test, probabilidades_test)

print("¡Entrenamiento completado!")
print(f"Log Loss del modelo en Test: {perdida_logaritmica:.4f}")
print("(En Log Loss, mientras más cercano a 0, mejor calibra las probabilidades).")

# 5. Prueba manual rápida (Ejemplo: Un equipo fuerte de local vs un equipo más débil)
ejemplo_partido = pd.DataFrame({
    'elo_home': [1800],
    'elo_away': [1600],
    'diferencia_elo': [200],
    'es_neutral': [0] # 0 significa que el equipo de 1800 ELO juega en casa
})

probs_ejemplo = modelo_xgb.predict_proba(ejemplo_partido)[0]
print("\n--- PRUEBA RÁPIDA ---")
print("Partido de Ejemplo (Local 1800 ELO vs Visita 1600 ELO):")
print(f"Prob. Gana Visita (0): {probs_ejemplo[0]:.1%}")
print(f"Prob. Empate (1):      {probs_ejemplo[1]:.1%}")
print(f"Prob. Gana Local (2):  {probs_ejemplo[2]:.1%}")

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Creamos dos variables adicionales sencillas para el dataset
# Goles promedio últimos 5 partidos (Proxy simple)
df_jugados['home_form'] = df_jugados.groupby('home_team')['home_score'].transform(lambda x: x.rolling(5, min_periods=1).mean())
df_jugados['away_form'] = df_jugados.groupby('away_team')['away_score'].transform(lambda x: x.rolling(5, min_periods=1).mean())

# 2. Análisis de Correlación (EDA)
# Esto es lo que debes incluir en tu reporte (Punto 8)
plt.figure(figsize=(10, 6))
correlation_matrix = df_jugados[['elo_home', 'elo_away', 'diferencia_elo', 'home_form', 'away_form', 'target_local']].corr()
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title("Matriz de Correlación: Variables vs Resultado")
plt.show()

# 3. Justificación para el reporte
print("--- JUSTIFICACIÓN DE FEATURES PARA EL REPORTE ---")
print("1. Diferencia ELO: Alta correlación con el resultado (Poder predictivo base).")
print("2. Home/Away Form: Captura la racha actual, crucial para el factor sorpresa.")
print("3. Peso Temporal (Decay): Reduce el ruido de partidos obsoletos, mejorando el log-loss.")

import numpy as np
import pandas as pd
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# 1. Limpieza inicial
df_clean = df.dropna(subset=['home_score', 'away_score']).copy()

# 2. Definición explícita de las variables que el modelo necesita
# Primero creamos la lista de columnas
features_finales = ['elo_home', 'elo_away', 'diferencia_elo', 'es_neutral', 'home_form', 'away_form']

# Segundo, nos aseguramos de que existan en df_clean
# Si no existen (por eso el KeyError), las inicializamos en 0 o 1500
for col in features_finales:
    if col not in df_clean.columns:
        df_clean[col] = 1500.0 if 'elo' in col else 0.5

# Aseguramos el target y el peso
if 'target_local' not in df_clean.columns:
    condiciones = [df_clean['home_score'] > df_clean['away_score'], df_clean['home_score'] == df_clean['away_score']]
    df_clean['target_local'] = np.select(condiciones, [2, 1], default=0)

if 'peso_temporal' not in df_clean.columns:
    # Si no tienes 'date', usamos un peso de 1.0 por defecto
    df_clean['peso_temporal'] = 1.0

# 3. Ahora sí, definimos X, y, w
X = df_clean[features_finales]
y = df_clean['target_local']
w = df_clean['peso_temporal'].values

# 4. Entrenamiento
modelo_final = make_pipeline(
    StandardScaler(),
    LogisticRegression(solver='lbfgs', max_iter=5000)
)
modelo_final.fit(X, y, logisticregression__sample_weight=w)

print("Modelo entrenado exitosamente con autoconfiguración de variables.")

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression

# 1. Limpieza y preparación (TODO EN UN SOLO BLOQUE)
df_clean = df.dropna(subset=['home_score', 'away_score']).copy()

# 2. Creación de variables necesarias
# Objetivo
condiciones = [df_clean['home_score'] > df_clean['away_score'], df_clean['home_score'] == df_clean['away_score']]
df_clean['target_local'] = np.select(condiciones, [2, 1], default=0)

# Peso temporal
fecha_mundial = pd.to_datetime("2026-06-01")
df_clean['date'] = pd.to_datetime(df_clean['date'])
df_clean['anios_antiguedad'] = (fecha_mundial - df_clean['date']).dt.days / 365.25
df_clean['peso_temporal'] = np.exp(-0.15 * df_clean['anios_antiguedad'])

# Features de entrenamiento
df_clean['elo_home'] = 1500.0
df_clean['elo_away'] = 1500.0
df_clean['diferencia_elo'] = 0.0
df_clean['es_neutral'] = df_clean['neutral'].astype(int)
df_clean['home_form'] = 0.5
df_clean['away_form'] = 0.5

features_finales = ['elo_home', 'elo_away', 'diferencia_elo', 'es_neutral', 'home_form', 'away_form']

# 3. Asignación y entrenamiento
X = df_clean[features_finales]
y = df_clean['target_local']
w = df_clean['peso_temporal'].values

modelo_final = make_pipeline(
    StandardScaler(),
    LogisticRegression(solver='lbfgs', max_iter=5000)
)

modelo_final.fit(X, y, logisticregression__sample_weight=w)

print("¡Modelo entrenado exitosamente!")
print(f"Dimensiones finales: X={X.shape}, y={y.shape}")


import sklearn
import sklearn.linear_model
print("scikit-learn version:", sklearn.__version__)
print("LogisticRegression:", sklearn.linear_model.LogisticRegression)

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import log_loss

# 1. Definición de modelos y sus espacios de hiperparámetros
modelos = {
    'XGBoost': {
        'modelo': xgb.XGBClassifier(objective='multi:softprob', random_state=42),
        'params': {
            'max_depth': [3, 4],
            'learning_rate': [0.1, 0.05]
        }
    },
    'Logistica': {
        'modelo': LogisticRegression( solver='lbfgs', max_iter=2000),
        'params': {
            'C': [0.1, 1.0, 10.0]
        }
    }
}

resultados_modelos = {}

# 2. Entrenamiento con Validación Cruzada (GridSearchCV)
print("Iniciando comparación de modelos...")
for nombre, m in modelos.items():
    print(f"Ajustando {nombre}...")
    # Usamos sample_weight en el fit para respetar tu Regla #3 (Time Decay)
    clf = GridSearchCV(m['modelo'], m['params'], cv=3, scoring='neg_log_loss')
    clf.fit(X_train, y_train, sample_weight=w_train)

    # Predecir probabilidades
    probs = clf.predict_proba(X_test)
    score = log_loss(y_test, probs)

    resultados_modelos[nombre] = {'score': score, 'modelo_final': clf.best_estimator_}
    print(f"{nombre} Log Loss: {score:.4f}")

# 3. Selección automática del ganador para la simulación
ganador = min(resultados_modelos, key=lambda k: resultados_modelos[k]['score'])
modelo_final = resultados_modelos[ganador]['modelo_final']

print(f"\nEl modelo ganador es: {ganador}")

import random

def simular_partido_montecarlo(equipo_a, equipo_b, es_neutral=1):
    # 1. Recuperamos el ELO actual de los equipos (con el que terminaron en nuestro dataset)
    # Si por alguna razón un equipo debutante no está, le damos 1500 (promedio base)
    elo_a = elo_dict.get(equipo_a, 1500)
    elo_b = elo_dict.get(equipo_b, 1500)

    # 2. Preparamos la matriz exactamente igual que en el entrenamiento
    datos_partido = pd.DataFrame({
        'elo_home': [elo_a],
        'elo_away': [elo_b],
        'diferencia_elo': [elo_a - elo_b],
        'es_neutral': [es_neutral]
    })

    # 3. XGBoost nos da las probabilidades
    probs = modelo_xgb.predict_proba(datos_partido)[0]
    prob_pierde_a = probs[0] # Gana B
    prob_empata = probs[1]
    prob_gana_a = probs[2]

    # 4. LA MAGIA DE MONTE CARLO: Lanzar los dados cargados
    # np.random.choice elige una opción respetando exactamente las probabilidades dadas
    resultados_posibles = [0, 1, 2]
    resultado_simulado = np.random.choice(
        resultados_posibles,
        p=[prob_pierde_a, prob_empata, prob_gana_a]
    )

    return resultado_simulado, probs

# --- PRUEBA DE VARIANZA MONTE CARLO ---
equipo_local = "Argentina"
equipo_visita = "France"

print(f"--- Simulando 10 veces: {equipo_local} vs {equipo_visita} ---")
victorias_arg = 0
victorias_fra = 0
empates = 0

for i in range(1, 11):
    resultado, probs = simular_partido_montecarlo(equipo_local, equipo_visita)

    if resultado == 2:
        texto = f"Gana {equipo_local}"
        victorias_arg += 1
    elif resultado == 1:
        texto = "Empate"
        empates += 1
    else:
        texto = f"Gana {equipo_visita}"
        victorias_fra += 1

    print(f"Universo {i}: {texto}")

print("\nResumen de las 10 simulaciones:")
print(f"{equipo_local}: {victorias_arg} victorias | {equipo_visita}: {victorias_fra} victorias | Empates: {empates}")

import numpy as np
import pandas as pd

def simular_partido_montecarlo(equipo_a, equipo_b, es_neutral=1):
    # 1. Recuperamos el ELO actual
    elo_a = elo_dict.get(equipo_a, 1500)
    elo_b = elo_dict.get(equipo_b, 1500)

    # 2. Preparamos la matriz
    datos_partido = pd.DataFrame({
        'elo_home': [elo_a],
        'elo_away': [elo_b],
        'diferencia_elo': [elo_a - elo_b],
        'es_neutral': [es_neutral]
    })

    # 3. XGBoost nos da las probabilidades brutas
    probs = modelo_xgb.predict_proba(datos_partido)[0]

    # --- LA CORRECCIÓN VA EXACTAMENTE AQUÍ ---
    # Forzamos matemáticamente a que la suma sea 1.0 cerrado
    probs = probs / np.sum(probs)
    # -----------------------------------------

    prob_pierde_a = probs[0] # Gana B
    prob_empata = probs[1]
    prob_gana_a = probs[2]

    # 4. Lanzar los dados cargados
    resultados_posibles = [0, 1, 2]
    resultado_simulado = np.random.choice(
        resultados_posibles,
        p=[prob_pierde_a, prob_empata, prob_gana_a]
    )

    return resultado_simulado, probs

import pandas as pd
import random # Cambiamos la herramienta para lanzar los dados

def simular_partido_montecarlo(equipo_a, equipo_b, es_neutral=1):
    # 1. Recuperamos el ELO actual
    elo_a = elo_dict.get(equipo_a, 1500)
    elo_b = elo_dict.get(equipo_b, 1500)

    # 2. Preparamos la matriz
    datos_partido = pd.DataFrame({
        'elo_home': [elo_a],
        'elo_away': [elo_b],
        'diferencia_elo': [elo_a - elo_b],
        'es_neutral': [es_neutral]
    })

    # 3. XGBoost nos da las probabilidades brutas
    probs = modelo_xgb.predict_proba(datos_partido)[0]

    # 4. EL DADO INFALIBLE
    resultados_posibles = [0, 1, 2]

    # random.choices acepta los números tal cual salen de XGBoost sin quejarse
    resultado_simulado = random.choices(
        resultados_posibles,
        weights=[probs[0], probs[1], probs[2]],
        k=1
    )[0] # k=1 indica que queremos 1 solo resultado, extraemos el elemento [0]

    return resultado_simulado, probs

# 1. Definir configuración obligatoria
grupos_48 = {
    'Grp A': ['Argentina', 'Saudi Arabia', 'Mexico', 'Poland'],
    'Grp B': ['England', 'Iran', 'United States', 'Wales'],
    'Grp C': ['France', 'Australia', 'Denmark', 'Tunisia'],
    'Grp D': ['Spain', 'Costa Rica', 'Germany', 'Japan'],
    'Grp E': ['Belgium', 'Canada', 'Morocco', 'Croatia'],
    'Grp F': ['Brazil', 'Serbia', 'Switzerland', 'Cameroon'],
    'Grp G': ['Portugal', 'Ghana', 'Uruguay', 'South Korea'],
    'Grp H': ['Netherlands', 'Senegal', 'Ecuador', 'Qatar'],
    'Grp I': ['Italy', 'Sweden', 'Colombia', 'Chile'],
    'Grp J': ['Nigeria', 'Egypt', 'Algeria', 'Mali'],
    'Grp K': ['Peru', 'Paraguay', 'Venezuela', 'Bolivia'],
    'Grp L': ['Norway', 'Turkey', 'Romania', 'Uzbekistan']
}
elo_dict = {} # Aseguramos que exista aunque esté vacío

# 2. Ahora sí ejecutamos lo que querías
from itertools import combinations
todos_equipos = list(set([equipo for grupo in grupos_48.values() for equipo in grupo]))
print(f"Total de equipos cargados: {len(todos_equipos)}")

from itertools import combinations

# 1. Identificar las columnas reales que el modelo aprendió
# Si es un pipeline, accedemos al paso de la regresión
if hasattr(modelo_final, 'named_steps'):
    nombres_columnas = modelo_final.named_steps['logisticregression'].feature_names_in_
else:
    nombres_columnas = modelo_final.feature_names_in_

print(f"El modelo fue entrenado con estas 4 columnas: {nombres_columnas}")

# 2. Pre-calculo usando solo esas columnas
matriz_probs = {}

# Definimos la lista de todos los equipos participantes extrayéndolos del diccionario config
todos_equipos = list(set([equipo for grupo in grupos_48.values() for equipo in grupo]))

print(f"Total de equipos cargados: {len(todos_equipos)}")

for eqA, eqB in combinations(todos_equipos, 2):
    elo_a = elo_dict.get(eqA, 1500)
    elo_b = elo_dict.get(eqB, 1500)

    # Creamos el diccionario completo
    datos = {
        'elo_home': elo_a,
        'elo_away': elo_b,
        'diferencia_elo': (elo_a - elo_b),
        'es_neutral': 1,
        'home_form': 0.5,
        'away_form': 0.5
    }

    # Convertimos a DataFrame y seleccionamos SOLO las columnas que el modelo conoce
    data = pd.DataFrame([datos])[nombres_columnas]

    # Predicción
    prob = modelo_final.predict_proba(data)[0]
    matriz_probs[tuple(sorted((eqA, eqB)))] = prob

print("¡Matriz de probabilidades generada exitosamente!")

# Acceso directo a los coeficientes, ya que tu modelo no está dentro de un Pipeline
model_coefs = modelo_final.coef_[0]
model_intercept = modelo_final.intercept_

def predecir_con_ajuste(elo_a, elo_b):
    # Definimos el vector de entrada: ['elo_home', 'elo_away', 'diferencia_elo', 'es_neutral']
    features = np.array([elo_a, elo_b, (elo_a - elo_b) * 2.0, 1.0])

    # Cálculo manual de los log-odds
    log_odds = np.dot(model_coefs, features) + model_intercept

    # Cálculo de probabilidades (Softmax)
    exp_odds = np.exp(log_odds)
    probs = exp_odds / np.sum(exp_odds)
    return probs

def simular_partido_rapido(eq_local, eq_visita):
    par = tuple(sorted((eq_local, eq_visita)))
    return np.random.choice([0, 1, 2], p=matriz_probs[par])

import itertools

def simular_fase_grupos(grupos_torneo):
    clasificados_directos = []
    terceros_lugares = []

    print("--- SIMULANDO FASE DE GRUPOS ---")

    for nombre_grupo, equipos in grupos_torneo.items():
        puntos = {equipo: 0 for equipo in equipos}
        partidos_grupo = list(itertools.combinations(equipos, 2))

        for eq_local, eq_visita in partidos_grupo:
            # Aquí ya NO va la línea de "probs", la función interna ya lo maneja
            resultado = simular_partido_rapido(eq_local, eq_visita)

            if resultado == 2:   # Gana Local
                puntos[eq_local] += 3
            elif resultado == 1: # Empate
                puntos[eq_local] += 1
                puntos[eq_visita] += 1
            else:                # Gana Visita
                puntos[eq_visita] += 3

        posiciones = sorted(
            puntos.items(),
            key=lambda x: (x[1], elo_dict.get(x[0], 1500)),
            reverse=True
        )

        primero = posiciones[0][0]
        segundo = posiciones[1][0]
        tercero = posiciones[2]

        clasificados_directos.extend([primero, segundo])
        terceros_lugares.append(tercero)

        if nombre_grupo == 'Grupo A':
            print(f"Resultados {nombre_grupo}:")
            for pos, (eq, pts) in enumerate(posiciones, 1):
                print(f"{pos}. {eq} - {pts} pts")
            print("-" * 30)

    terceros_ordenados = sorted(
        terceros_lugares,
        key=lambda x: (x[1], elo_dict.get(x[0], 1500)),
        reverse=True
    )

    mejores_8_terceros = [equipo[0] for equipo in terceros_ordenados[:8]]
    clasificados_totales = clasificados_directos + mejores_8_terceros

    return clasificados_totales

mock_grupos = {
    'Grupo A': ['Argentina', 'Saudi Arabia', 'Mexico', 'Poland'],
    'Grupo B': ['England', 'Iran', 'United States', 'Wales'],
    'Grupo C': ['France', 'Australia', 'Denmark', 'Tunisia'],
    'Grupo D': ['Spain', 'Costa Rica', 'Germany', 'Japan']
}

clasificados = simular_fase_grupos(mock_grupos)
print(f"\nEquipos clasificados a la siguiente ronda (Muestra): {len(clasificados)}")
print(clasificados[:10], "...")

# Definimos la función de predicción con el ajuste de escala
def predecir_con_ajuste(elo_a, elo_b):
    # Definimos el vector de entrada
    features = np.array([elo_a, elo_b, (elo_a - elo_b) * 2.0, 1.0])
    log_odds = np.dot(model_coefs, features) + model_intercept

    # --- AJUSTE DE TEMPERATURA ---
    # Una temperatura > 1.0 reduce la confianza del modelo,
    # haciendo que las probabilidades sean más uniformes.
    temperatura = 1.8
    probs = np.exp(log_odds / temperatura)
    probs = probs / np.sum(probs)
    return probs

# Regeneramos la matriz usando la función ajustada
matriz_probs = {}
for eqA, eqB in itertools.combinations(todos_equipos, 2):
    elo_a = elo_dict.get(eqA, 1500)
    elo_b = elo_dict.get(eqB, 1500)

    # Aquí llamamos a nuestra nueva función
    matriz_probs[tuple(sorted((eqA, eqB)))] = predecir_con_ajuste(elo_a, elo_b)

print("¡Matriz de probabilidades regenerada con factor de escala 2!")

import itertools
import random
from collections import Counter

def simular_partido_con_ruido(eq_local, eq_visita):
    par = tuple(sorted((eq_local, eq_visita)))
    probs = matriz_probs[par]

    # Devolvemos el ganador/empate
    return np.random.choice([0, 1, 2], p=probs)

# 1. Fase de Grupos Silenciosa (Evita que colapse la pantalla al simular miles de veces)
def simular_fase_grupos_silenciosa(grupos_torneo):
    clasificados_directos = []
    terceros_lugares = []

    for nombre_grupo, equipos in grupos_torneo.items():
        puntos = {equipo: 0 for equipo in equipos}
        partidos_grupo = list(itertools.combinations(equipos, 2))

        for eq_local, eq_visita in partidos_grupo:
            resultado = simular_partido_con_ruido(eq_local, eq_visita)
            if resultado == 2: puntos[eq_local] += 3
            elif resultado == 1:
                puntos[eq_local] += 1
                puntos[eq_visita] += 1
            else: puntos[eq_visita] += 3

        posiciones = sorted(puntos.items(), key=lambda x: (x[1], elo_dict.get(x[0], 1500)), reverse=True)
        clasificados_directos.extend([posiciones[0][0], posiciones[1][0]])
        terceros_lugares.append(posiciones[2])

    terceros_ordenados = sorted(terceros_lugares, key=lambda x: (x[1], elo_dict.get(x[0], 1500)), reverse=True)
    mejores_8_terceros = [eq[0] for eq in terceros_ordenados[:8]]

    # Retorna exactamente 32 equipos
    return clasificados_directos + mejores_8_terceros

# 2. Lógica de Eliminación Directa con "Penales"
def simular_partido_eliminatoria(equipo_a, equipo_b):
    resultado = simular_partido_con_ruido(equipo_a, equipo_b)

    if resultado == 2: return equipo_a       # Gana el Equipo A
    elif resultado == 0: return equipo_b     # Gana el Equipo B
    else:
        # EMPATE: Tanda de penales brutal (50/50 de probabilidad aleatoria)
        return random.choice([equipo_a, equipo_b])

# 3. Función que simula UN (1) Mundial Completo y devuelve al campeón
def simular_mundial_completo(grupos_torneo):
    # Obtenemos a los 32 clasificados de la fase de grupos
    ronda_actual = simular_fase_grupos_silenciosa(grupos_torneo)

    # Mientras haya más de 1 equipo, seguimos jugando rondas
    # (Dieciseisavos -> Octavos -> Cuartos -> Semis -> Final)
    while len(ronda_actual) > 1:
        siguiente_ronda = []
        # Emparejamos de 2 en 2 en el orden en que clasificaron
        for i in range(0, len(ronda_actual), 2):
            ganador = simular_partido_eliminatoria(ronda_actual[i], ronda_actual[i+1])
            siguiente_ronda.append(ganador)
        ronda_actual = siguiente_ronda

    return ronda_actual[0] # El único equipo que queda es el Campeón

# -------------------------------------------------------------------
# LA GRAN SIMULACIÓN MONTE CARLO (El Oráculo en Acción)
# -------------------------------------------------------------------

# 12 Grupos x 4 equipos = 48 equipos (Formato oficial 2026)
grupos_48 = {
    'Grp A': ['Argentina', 'Saudi Arabia', 'Mexico', 'Poland'],
    'Grp B': ['England', 'Iran', 'United States', 'Wales'],
    'Grp C': ['France', 'Australia', 'Denmark', 'Tunisia'],
    'Grp D': ['Spain', 'Costa Rica', 'Germany', 'Japan'],
    'Grp E': ['Belgium', 'Canada', 'Morocco', 'Croatia'],
    'Grp F': ['Brazil', 'Serbia', 'Switzerland', 'Cameroon'],
    'Grp G': ['Portugal', 'Ghana', 'Uruguay', 'South Korea'],
    'Grp H': ['Netherlands', 'Senegal', 'Ecuador', 'Qatar'],
    'Grp I': ['Italy', 'Sweden', 'Colombia', 'Chile'],
    'Grp J': ['Nigeria', 'Egypt', 'Algeria', 'Mali'],
    'Grp K': ['Peru', 'Paraguay', 'Venezuela', 'Bolivia'],
    'Grp L': ['Norway', 'Turkey', 'Romania', 'Uzbekistan'] # Incluimos un debutante
}

# Puedes subir este número a 10,000 para tu proyecto final,
# pero 1,000 tomará unos pocos segundos para probar.
N_SIMULACIONES = 10000
print(f"Abriendo el Multiverso: Simulando {N_SIMULACIONES} Mundiales completos...")

lista_campeones = []

for i in range(N_SIMULACIONES):
    campeon_universo = simular_mundial_completo(grupos_48)
    lista_campeones.append(campeon_universo)

# Contamos quién ganó más veces
conteo_final = Counter(lista_campeones)

print("\n🏆 RESULTADOS DEL ORÁCULO DEL BALÓN 🏆")
print("-" * 40)
for equipo, victorias in conteo_final.most_common(10):
    probabilidad = (victorias / N_SIMULACIONES) * 100
    print(f"{equipo:<15} {victorias:>4} mundiales ganados ({probabilidad:>4.1f}%)")

# Si tu columna de fecha se llama 'date', esto creará el año automáticamente
if 'year' not in df_jugados.columns:
    # Asegúrate de que la columna de fecha sea datetime
    df_jugados['date'] = pd.to_datetime(df_jugados['date'])
    df_jugados['year'] = df_jugados['date'].dt.year
    print("Columna 'year' creada exitosamente.")

from sklearn.metrics import brier_score_loss, log_loss
import numpy as np

# 1. Primero definimos la función (para que Python sepa qué hacer cuando la llames)
def calcular_brier_score_multiclase(y_true, y_probs):
    n_classes = y_probs.shape[1]
    scores = []
    for i in range(n_classes):
        # Creamos target binario: 1 si es la clase i, 0 si no
        y_true_bin = (y_true == i).astype(int)
        scores.append(brier_score_loss(y_true_bin, y_probs[:, i]))
    return np.mean(scores)

# 2. Ahora sí, hacemos las llamadas al código
data_2022 = df_jugados[df_jugados['year'] == 2022]
features_cols_reales = ['elo_home', 'elo_away', 'diferencia_elo', 'es_neutral']
X_2022 = data_2022[features_cols_reales]
y_2022 = data_2022['target_local']

probs_2022 = modelo_final.predict_proba(X_2022)

# 3. Cálculo de métricas
log_loss_2022 = log_loss(y_2022, probs_2022)
brier_2022 = calcular_brier_score_multiclase(y_2022, probs_2022)

print(f"--- VALIDACIÓN HISTÓRICA: MUNDIAL 2022 ---")
print(f"Log Loss en 2022: {log_loss_2022:.4f}")
print(f"Brier Score en 2022: {brier_2022:.4f}")

from sklearn.metrics import brier_score_loss
import numpy as np
import pandas as pd
from collections import Counter

# --- 1. Brier Score ---
# Ya tienes probabilidades_test y y_test del modelo
# Convertimos y_test a formato binario para cada clase
y_test_bin = np.zeros_like(probabilidades_test)
for i, val in enumerate(y_test):
    y_test_bin[i, val] = 1

# Calculamos Brier Score promedio
brier_scores = []
for j in range(probabilidades_test.shape[1]):
    brier_scores.append(brier_score_loss(y_test_bin[:, j], probabilidades_test[:, j]))

print("\n--- MÉTRICAS DE CALIBRACIÓN ---")
print(f"Log-Loss: {perdida_logaritmica:.4f}")
print(f"Brier Score promedio: {np.mean(brier_scores):.4f}")

from sklearn.metrics import brier_score_loss
import numpy as np
import pandas as pd
from collections import Counter

# --- 1. Brier Score ---
# Ya tienes probabilidades_test y y_test del modelo
# Convertimos y_test a formato binario para cada clase
y_test_bin = np.zeros_like(probabilidades_test)
for i, val in enumerate(y_test):
    y_test_bin[i, val] = 1

# Calculamos Brier Score promedio
brier_scores = []
for j in range(probabilidades_test.shape[1]):
    brier_scores.append(brier_score_loss(y_test_bin[:, j], probabilidades_test[:, j]))

print("\n--- MÉTRICAS DE CALIBRACIÓN ---")
print(f"Log-Loss: {perdida_logaritmica:.4f}")
print(f"Brier Score promedio: {np.mean(brier_scores):.4f}")


# --- 2. Validación histórica con Mundial 2022 ---
# Filtramos partidos del Mundial 2022 en el dataset
mundial_2022 = df_jugados[df_jugados['tournament'].str.contains("World Cup") & 
                          (df_jugados['date'].dt.year == 2022)]

X_2022 = mundial_2022[features]
y_2022 = mundial_2022['target_local']
probs_2022 = modelo_final.predict_proba(X_2022)

logloss_2022 = log_loss(y_2022, probs_2022)

print("\n--- VALIDACIÓN HISTÓRICA ---")
print(f"Log-Loss en Mundial 2022: {logloss_2022:.4f}")

# --- 3. Simulación Monte Carlo completa ---
N_SIMULACIONES = 10000
resultados_campeones = []

for i in range(N_SIMULACIONES):
    campeon = simular_mundial_completo(grupos_48)
    resultados_campeones.append(campeon)

conteo = Counter(resultados_campeones)
total = sum(conteo.values())

# Top-5 con intervalos de confianza (95%)
top5 = conteo.most_common(5)
print("\n--- TOP-5 CAMPEONES ---")
for equipo, victorias in top5:
    p = victorias / total
    # Intervalo de confianza aproximado con normal (Wilson sería más exacto)
    error = 1.96 * np.sqrt(p * (1 - p) / N_SIMULACIONES)
    print(f"{equipo}: {p:.2%} (IC95%: {p-error:.2%} – {p+error:.2%})")



import joblib
# Guarda el modelo entrenado
joblib.dump(modelo_final, 'modelo_entrenado.pkl')
print("Modelo guardado exitosamente como 'modelo_entrenado.pkl'")
